### PR TITLE
add security code and docker

### PR DESCRIPTION
**Pull request by jon4hz**
As you can see I added the security code in the config.py file and check it at the same time as the whitelist.
I also added a Dockerfile and docker-compose.yml file for those who like to run it inside a container.

### CODE REVIEW

**Comment by TheDevFab** [comment]
Awesome, thank you - appreciate it!

**Comment by jon4hz** [comment]
You're welcome ^^

**Comment by Rhydderch** [comment]
What should I do to use this security code ?
I am getting this error
image

**Comment by vsnz** [comment]
Hi @Rhydderch, I replied to your issue in #18.

**Pull request merged**
